apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 5000                  
      nodePort: {{ .Values.backend.service.nodePort }}
  type: NodePort