apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  
      targetPort: 80                  
      nodePort: {{ .Values.service.nodePort }} # Optional: The external port exposed on your machine
  type: NodePort