apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
          ports:
            - name: api-port
              containerPort: 5000
#        - name: tests
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#          command: ["pytest", "test_app.py"]
#          env:
#            - name: MONGO_URI
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: MONGO_URI
