apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 # This is the port the service exposes within the cluster
      targetPort: 5000
  type: ClusterIP
